### ISSUE TITLE
Django error when running on openshift Connection.__init__() got an unexpected keyword argument 'ssl_cert_reqs'

### ISSUE THREAD

**Issue by joyartoun** [bootc/netbox-chart#133]
Hello,

we are trying to use this chart on openshift, however we get an error seemingly related to the following Django ticket https://github.com/jazzband/django-redis/issues/353. 

We are using the latest chart 4.1.1 with the redis-ha chart from dandydeveloper https://dandydeveloper.github.io/charts 

These are the following values that have been overridden: 
netbox-chart:

```
      - name: replicaCount
        value: '1'
        forceString: true
      - name: securityContext.runAsUser
        value: '1000920000'
      - name: securityContext.runAsGroup
        value: '1000920000'
      - name: init.securityContext.runAsUser
        value: '1000920000'
      - name: init.securityContext.runAsGroup
        value: '1000920000'
      - name: podSecurityContext.fsGroup
        value: '1000920000'
      - name: worker.securityContext.runAsUser
        value: '1000920000'
      - name: worker.securityContext.runAsGroup
        value: '1000920000'
      - name: worker.podSecurityContext.fsGroup
        value: '1000920000'
      - name: postgresql.enabled
        value: 'false'
      - name: externalDatabase.host
        value: netbox-psql-postgresql
      - name: externalDatabase.existingSecretName
        value: netbox-credentials
      - name: externalDatabase.existingSecretKey
        value: password
      - name: persistence.accessMode
        value: ReadWriteMany
      - name: existingSecret
        value: netbox
      - name: superuser.name
        value: <redacted>
      - name: housekeeping.securityContext.runAsUser
        value: '1000920000'
      - name: housekeeping.securityContext.runAsGroup
        value: '1000920000'
      - name: housekeeping.podSecurityContext.fsGroup
        value: '1000920000'
      - name: remoteAuth.enabled
        value: 'true'
      - name: debug
        value: 'true'
      - name: redis.enabled
        value: 'false'
      - name: tasksRedis.existingSecretName
        value: netbox-redis
      - name: cachingRedis.existingSecretName
        value: netbox-redis
      - name: cachingRedis.existingSecretKey
        value: sentinel-password
      - name: tasksRedis.existingSecretKey
        value: sentinel-password
      - name: tasksRedis.insecureSkipTlsVerify
        value: 'true'
      - name: cachingRedis.insecureSkipTlsVerify
        value: 'true'
      - name: tasksRedis.host
        value: netbox-redis-redis-ha
      - name: cachingRedis.host
        value: netbox-redis-redis-ha
      - name: 'tasksRedis.sentinels[0]'
        value: 'netbox-redis-redis-ha-announce-0:26379'
      - name: 'tasksRedis.sentinels[1]'
        value: 'netbox-redis-redis-ha-announce-1:26379'
      - name: 'tasksRedis.sentinels[2]'
        value: 'netbox-redis-redis-ha-announce-2:26379'
      - name: tasksRedis.sentinelService
        value: netbox-redis-redis-ha
      - name: 'cachingRedis.sentinels[0]'
        value: 'netbox-redis-redis-ha-announce-0:26379'
      - name: 'cachingRedis.sentinels[1]'
        value: 'netbox-redis-redis-ha-announce-1:26379'
      - name: 'cachingRedis.sentinels[2]'
        value: 'netbox-redis-redis-ha-announce-2:26379'
      - name: cachingRedis.sentinelService
        value: netbox-redis-redis-ha
      - name: image.tag
        value: v3.4.2
```
redis-ha chart:

```
replicas
 3
redis.config.min-replicas-to-write
 0
redis.masterGroupName
 redismaster
containerSecurityContext.runAsUser
 1000920000
haproxy.securityContext.runAsUser
 1000920000
haproxy.securityContext.fsGroup
 1000920000
securityContext.runAsUser
 1000920000
securityContext.fsGroup
 1000920000
existingSecret
 netbox-redis
authKey
 redis-password
auth
 false
sentinel.auth
 false
sentinel.existingSecret
 netbox-redis
sentinel.authKey
 sentinel-password
 ```
 
![error](https://user-images.githubusercontent.com/29835230/212656571-e5faa746-0821-41a9-83f7-ce474adea463.png)

 Please help us understand if this is a configuration error or in fact a bug in Django. 
 We have tried different ways of specifying the variables in the chart but there is never any change, always the same problem.

**Comment by bootc** [comment]
You don't seem to be configuring TLS for `redis-ha`, nor are you trying to connect to it with TLS, so you probably shouldn't set the `insecureSkipTlsVerify` key under either `tasksRedis` or `cachingRedis`.

**Comment by joyartoun** [comment]
@bootc thanks for a quick answer.

It is true we are not using TLS, hence we have set insecureSkipTlsVerify to true for caching and task redis, because we want to skip TLS.

**Comment by bootc** [comment]
That's not what it means though. It means "when using TLS, don't bother checking the certificate". In this case it triggers passing of SSL options to a Redis client instance that doesn't know what to do with them.

By the way this is an issue within the Redis client itself, not a problem with the chart, or our upstream [netbox-docker](https://github.com/netbox-community/netbox-docker) project, or even NetBox itself.

**Comment by joyartoun** [comment]
Hi @bootc thanks, I understand now. Is it possible to completely disable the TLS altogether? The chart seems to set the parameter to True if nothing is specified. Could I just specify them with a empty string?

**Comment by bootc** [comment]
No the chart's defaults are to set them to be false:
https://github.com/bootc/netbox-chart/blob/dde8cfd498373499bb4970567904129a0202c397/values.yaml#L403-L406
https://github.com/bootc/netbox-chart/blob/dde8cfd498373499bb4970567904129a0202c397/values.yaml#L420-L423
Now that you've set them to true you may need to explicitly reset them to false, or otherwise pass `--reset-values` to Helm to get the default values back.

**Comment by joyartoun** [comment]
yes Sorry, I mean that default is False of course..I now actually get a little bit further it seems. However the netbox pod fails with 

```
File "/opt/netbox/venv/lib/python3.10/site-packages/redis/sentinel.py", line 138, in rotate_slaves
raise SlaveNotFoundError(f"No slave found for {self.service_name!r}")
redis.sentinel.SlaveNotFoundError: No slave found for 'netbox-redis-redis-ha'
```
Which in my opinion is strange because the sentinel service is reporting that there are two slaves
```
/data $ redis-cli -p 26379
127.0.0.1:26379> sentinel masters
1)  1) "name"
    2) "redismaster"
    3) "ip"
    4) "10.230.184.136"
    5) "port"
    6) "6379"
    7) "runid"
    8) "c8b9721254f564f5a9f1fd8af3e1aea8d0483900"
    9) "flags"
   10) "master"
   11) "link-pending-commands"
   12) "0"
   13) "link-refcount"
   14) "1"
   15) "last-ping-sent"
   16) "0"
   17) "last-ok-ping-reply"
   18) "159"
   19) "last-ping-reply"
   20) "159"
   21) "down-after-milliseconds"
   22) "10000"
   23) "info-refresh"
   24) "9611"
   25) "role-reported"
   26) "master"
   27) "role-reported-time"
   28) "11482553"
   29) "config-epoch"
   30) "0"
   31) "num-slaves"
   32) "2"
   33) "num-other-sentinels"
   34) "2"
   35) "quorum"
   36) "2"
   37) "failover-timeout"
   38) "180000"
   39) "parallel-syncs"
   40) "5"
```
I have verified that the service netbox-redis-redis-ha goes two all three replicas of redis/sentinel and both ports for redis and sentinels are active on that service

**Comment by bootc** [comment]
You've configured your Sentinel master group name to be `redismaster`:
> ```
> redis.masterGroupName
>  redismaster
> ```
So you need to configure the two `sentinelService` settings to the same value.

**Comment by joyartoun** [comment]
Still the same problem sadly.

From netbox pod 
```
/opt/netbox/venv/lib/python3.10/site-packages/django/views/debug.py:473: ExceptionCycleWarning: Cycle in the exception chain detected: exception 'No slave found for 'redismaster'' encountered again.
warnings.warn(
.........
.........
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/sentinel.py", line 138, in rotate_slaves
    raise SlaveNotFoundError(f"No slave found for {self.service_name!r}")
redis.sentinel.SlaveNotFoundError: No slave found for 'redismaster'
2023/01/16 13:22:59 [info] 18#24 *21 send(99, 7FA0223FE000, 158113) failed (32: Broken pipe)
10.130.6.1 - - [16/Jan/2023:13:22:59 +0000] "GET /login/ HTTP/1.1" 500 0 "-" "kube-probe/1.24"
Internal Server Error: /login/
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 31, in _decorator
    return method(self, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 98, in _get
    return self.client.get(key, default=default, version=version, client=client)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 260, in get
    raise ConnectionInterrupted(connection=client) from e
django_redis.exceptions.ConnectionInterrupted: Redis SlaveNotFoundError: No slave found for 'redismaster'
```

From netbox-worker pod:
```
No queues have been specified. This process will service the following queues by default: high, default, low
No master found for 'redismaster'
🧬 loaded config '/etc/netbox/config/configuration.py'
🧬 loaded config '/etc/netbox/config/extra.py'
🧬 loaded config '/etc/netbox/config/logging.py'
🧬 loaded config '/etc/netbox/config/plugins.py'
```

I have even verified with copying the redis-cli binary to the netbox pod that the netbox pod can reach the redis-sentinel pods

**Comment by joyartoun** [comment]
Whole stacktrace from netbox pod

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/netbox/netbox/users/views.py", line 41, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/netbox/netbox/users/views.py", line 78, in get
    return render(request, self.template_name, {
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/netbox/venv/lib/python3.10/site-packages/debug_toolbar/panels/templates/panel.py", line 45, in _request_context_bind_template
    context = processor(self.request)
  File "/opt/netbox/netbox/netbox/context_processors.py", line 13, in settings_and_registry
    'config': get_config(),
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 27, in get_config
    _thread_locals.config = Config()
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 47, in __init__
    self._populate_from_cache()
  File "/opt/netbox/netbox/netbox/config/__init__.py", line 70, in _populate_from_cache
    self.config = cache.get('config') or {}
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 91, in get
    value = self._get(key, default, version, client)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.__cause__
  File "/opt/netbox/venv/lib/python3.10/site-packages/django_redis/client/default.py", line 258, in get
    value = client.get(key)
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1728, in get
    return self.execute_command("GET", name)
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/client.py", line 1255, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/connection.py", line 1389, in get_connection
    connection.connect()
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/sentinel.py", line 54, in connect
    return self.retry.call_with_retry(self._connect_retry, lambda error: None)
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/sentinel.py", line 46, in _connect_retry
    for slave in self.connection_pool.rotate_slaves():
  File "/opt/netbox/venv/lib/python3.10/site-packages/redis/sentinel.py", line 138, in rotate_slaves
    raise SlaveNotFoundError(f"No slave found for {self.service_name!r}")
redis.sentinel.SlaveNotFoundError: No slave found for 'redismaster'
```

**Comment by bootc** [comment]
I'm not sure what's going on here to be honest, I have a similar config working for my personal NetBox instance. My only observations are:

1. If you have `auth` and `sentinel.auth` disabled in Redis HA, why are you creating and referencing the `netbox-redis` Secret at all? At best it's not used at all and at worst it could be interfering similar to how the TLS settings were.
2. As you're using Sentinel you probably shouldn't be setting `tasksRedis.host` or `cachingRedis.host` as the Sentinel takes care of that.

Please double-check you haven't changed your redis-ha `redis.masterGroupName` setting away from `redismaster`, or if you have that the `tasksRedis.sentinelService` and `tasksRedis.sentinelService` are set to the same value. This isn't related to the actual Kubernetes service name used by Redis, it's the string value that NetBox needs to ask the Sentinel for so they have to have matching values.

**Comment by joyartoun** [comment]
@bootc thanks for all the help... According to this netbox issue https://github.com/netbox-community/netbox/issues/7817 

It is not possible for the netbox application to use sentinel with password authentication. Removed that and it started working.

Just going to print my values for both charts here in case someone stumbles across the same problem. 

netbox-chart: 
```
      - name: skipStartupScripts
        value: 'false'
      - name: replicaCount
        value: '3'
        forceString: true
      - name: securityContext.runAsUser
        value: '1000920000'
      - name: securityContext.runAsGroup
        value: '1000920000'
      - name: init.securityContext.runAsUser
        value: '1000920000'
      - name: init.securityContext.runAsGroup
        value: '1000920000'
      - name: podSecurityContext.fsGroup
        value: '1000920000'
      - name: worker.securityContext.runAsUser
        value: '1000920000'
      - name: worker.securityContext.runAsGroup
        value: '1000920000'
      - name: worker.podSecurityContext.fsGroup
        value: '1000920000'
      - name: postgresql.enabled
        value: 'false'
      - name: externalDatabase.host
        value: netbox-psql-postgresql
      - name: externalDatabase.existingSecretName
        value: netbox-credentials
      - name: externalDatabase.existingSecretKey
        value: password
      - name: persistence.accessMode
        value: ReadWriteMany
      - name: existingSecret
        value: netbox
      - name: superuser.name
        value: <redacted>
      - name: housekeeping.securityContext.runAsUser
        value: '1000920000'
      - name: housekeeping.securityContext.runAsGroup
        value: '1000920000'
      - name: housekeeping.podSecurityContext.fsGroup
        value: '1000920000'
      - name: redis.enabled
        value: 'false'
      - name: tasksRedis.existingSecretName
        value: netbox-redis
      - name: cachingRedis.existingSecretName
        value: netbox-redis
      - name: cachingRedis.existingSecretKey
        value: redis-password
      - name: tasksRedis.existingSecretKey
        value: redis-password
      - name: tasksRedis.insecureSkipTlsVerify
        value: 'false'
      - name: cachingRedis.insecureSkipTlsVerify
        value: 'false'
      - name: 'tasksRedis.sentinels[0]'
        value: 'netbox-redis-redis-ha-announce-0:26379'
      - name: 'tasksRedis.sentinels[1]'
        value: 'netbox-redis-redis-ha-announce-1:26379'
      - name: 'tasksRedis.sentinels[2]'
        value: 'netbox-redis-redis-ha-announce-2:26379'
      - name: tasksRedis.sentinelService
        value: redismaster
      - name: 'cachingRedis.sentinels[0]'
        value: 'netbox-redis-redis-ha-announce-0:26379'
      - name: 'cachingRedis.sentinels[1]'
        value: 'netbox-redis-redis-ha-announce-1:26379'
      - name: 'cachingRedis.sentinels[2]'
        value: 'netbox-redis-redis-ha-announce-2:26379'
      - name: cachingRedis.sentinelService
        value: redismaster
      - name: image.tag
        value: v3.4.2
```
redis-ha chart:
```
      - name: replicas
        value: '3'
      - name: redis.config.min-replicas-to-write
        value: '0'
      - name: redis.masterGroupName
        value: redismaster
      - name: containerSecurityContext.runAsUser
        value: '1000920000'
      - name: securityContext.runAsUser
        value: '1000920000'
      - name: securityContext.fsGroup
        value: '1000920000'
      - name: existingSecret
        value: netbox-redis
      - name: authKey
        value: redis-password
      - name: auth
        value: 'true'
      - name: sentinel.auth
        value: 'false'
      - name: sentinel.existingSecret
        value: netbox-redis
      - name: image.tag
        value: 7.0.7-alpine3.17
```

Thanks again
