### ISSUE TITLE
plugin usage not working - Module not found

### ISSUE THREAD

**Issue by rgarcia89** [bootc/netbox-chart#30]
When trying to installed some additional plugins following the instructions on https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins

```
FROM netboxcommunity/netbox:latest-ldap

COPY ./plugin_requirements.txt /
RUN /opt/netbox/venv/bin/pip install --no-cache --no-warn-script-location -r /plugin_requirements.txt
```

where plugin_requirements.txt looks like
```
netbox-plugin-auth-saml2
django3-auth-saml2
```

I get the following issue when starting netbox
```
ModuleNotFoundError: No module named 'django3-auth-saml2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/base.py", line 82, in wrapped
    saved_locale = translation.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 83, in __getattr__
    self._setup(name)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 70, in _setup
    self._wrapped = Settings(settings_module)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 177, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/settings.py", line 594, in <module>
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Unable to import plugin django3-auth-saml2: Module not found. Check that the plugin module has been installed within the correct Python environment.
```

I am overwriting the extras.py with a configmap that for now includes the following:
```
  extra.py: |
    PLUGINS = ['django3-auth-saml2']
```

Someone having an idea?

**Comment by rgarcia89** [comment]
wrong repo

**Comment by holmesb** [comment]
@rgarcia89, I'm getting same error when trying to install a plugin. Could you give more info how you fixed this?
