### ISSUE TITLE
 Vanilla install upgrade using Helm fails from 2.6.12 to 2.7.6

### ISSUE THREAD

**Issue by eric-dynamicops** [bootc/netbox-chart#90]
### NetBox version

v2.6.12

### Python version

3.7

### Steps to Reproduce

1. Clean install of Netbox, using Helm chart 1.0.4
2. Add some basic data
3. Upgrade to next version of Helm chart 2.0.0

### Expected Behavior

Expected to have a smooth process and running new version of Netbox

### Observed Behavior

All Pods except the Netbox one come up, i.e. PostgreSQL and Redis no problem, but Netbox Pod throws the below error, even though nothing has been changed from the defaults / user passwords stored in secrets.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "netbox"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 87, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 73, in applied_migrations
    if self.has_table():
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "netbox"

❌ Waited 30s or more for the DB to become ready.
```

Kind regards, 

Eric

**Comment by bootc** [comment]
I think you've been bitten by not explicitly setting the PostgreSQL password. There's now a note in the README about this: https://github.com/bootc/netbox-chart/tree/master#bundled-postgresql.

**Comment by eric-dynamicops** [comment]
Hi Chris, 

Thanks to your indication I found how to upgrade from 2.6.12 to 2.7.6. But now on the next version 2.7.7, using Helm chart version 2.0.1, it complains about the permissions on the data directory, while I have made no changes to anything.

```
╰─$ (⎈ aops-inf-gke01:netbox-testing) k logs netboxtest-postgresql-0
postgresql 10:36:48.89
postgresql 10:36:48.89 Welcome to the Bitnami postgresql container
postgresql 10:36:48.90 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-postgresql
postgresql 10:36:48.90 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-postgresql/issues
postgresql 10:36:48.90 Send us your feedback at containers@bitnami.com
postgresql 10:36:48.90
postgresql 10:36:48.92 INFO  ==> ** Starting PostgreSQL setup **
postgresql 10:36:48.98 INFO  ==> Validating settings in POSTGRESQL_* env vars..
postgresql 10:36:48.99 INFO  ==> Loading custom pre-init scripts...
postgresql 10:36:48.99 INFO  ==> Initializing PostgreSQL database...
postgresql 10:36:49.00 INFO  ==> postgresql.conf file not detected. Generating it...
postgresql 10:36:49.01 INFO  ==> pg_hba.conf file not detected. Generating it...
postgresql 10:36:49.02 INFO  ==> Generating local authentication configuration
postgresql 10:36:49.03 INFO  ==> Deploying PostgreSQL with persisted data...
postgresql 10:36:49.03 INFO  ==> Configuring replication parameters
postgresql 10:36:49.06 INFO  ==> Configuring fsync
postgresql 10:36:49.07 INFO  ==> Loading custom scripts...
postgresql 10:36:49.07 INFO  ==> Enabling remote connections
postgresql 10:36:49.08 INFO  ==> Stopping PostgreSQL...

postgresql 10:36:49.09 INFO  ==> ** PostgreSQL setup finished! **
postgresql 10:36:49.14 INFO  ==> ** Starting PostgreSQL **
2022-04-04 10:36:49.163 GMT [1] FATAL:  data directory "/bitnami/postgresql/data" has invalid permissions
2022-04-04 10:36:49.163 GMT [1] DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750).
╭─ericvs@Erics-MacBook-Pro-2 ~
╰─$ (⎈ aops-inf-gke01:netbox-testing)
```

Any idea what might trigger this error? 

Kind regards, 

Eric

**Comment by bootc** [comment]
Presumably you're upgrading the chart from [2.0.0 to 2.0.1](https://github.com/bootc/netbox-chart/compare/2.0.0...2.0.1), is that right? There are no changes to the chart w.r.t. PostgreSQL between those versions, though the bundled upstream chart goes from 8.3.4 to 8.4.0. That's outside my control, you'd have to refer to the upstream chart for such things. In this case, however, you can probably set `postgresql.volumePermissions.enabled=true` to fix this particular issue.

I recommend against using the bundled PostgreSQL and Redis charts for general use: 
https://github.com/bootc/netbox-chart/tree/develop#production-usage
(Admittedly that text is in an as-yet unreleased version of the chart, so I'm not surprised you didn't see it!)

Later versions of the chart switch to the Bitnami PostgreSQL and Redis charts which have _significant_ changes and you won't be able to upgrade without a dump/delete/reinstall/restore process.
